#!/usr/bin/env python3
from pathlib import Path
from settings.exceptions import CantGetCoordinates, ApiServiceError
from app.gps_coordinates import get_gps_coordinate
from app.save_history import save_weather, JSONFileWeatherStorage
from app.weather_api_service import get_weather_data
from app.weather_formatter import format_weather


def main():
    """Запуск приложение погоды 2.0"""
    try:
        coordinates = get_gps_coordinate()
    except CantGetCoordinates:
        print('Не удалось получить GPS координаты.')
        exit(1)
    try:
        weather_data = get_weather_data(coordinates)
    except ApiServiceError:
        print(f'Не удалось получить погоду по заданным координатам {coordinates}.')
        exit(1)
    print(format_weather(weather_data))

    save_weather(
        weather=weather_data,
        storage=JSONFileWeatherStorage(Path.cwd() / 'history.json')
    )


if __name__ == '__main__':
    main()
